apiVersion: v1
kind: Service
metadata:
  name: client-node-port
  namespace: default
spec:
  selector:
    app: web
    component: web
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 31515
