apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: 966339691353.dkr.ecr.us-west-2.amazonaws.com/nodejs-demo:latest
          ports:
            - containerPort: 3000
